import { Injectable } from '@angular/core';
import { Candidate, CandidateStatus } from '../../core/models/candidate.model';

@Injectable({ providedIn: 'root' })
export class CandidateService {
  private candidates: Candidate[] = [
    { id: '1', firstName: 'Sarah', lastName: 'Johnson', email: 'sarah.johnson@email.com', phoneNumber: '+1 (555) 123-4567', clientName: 'TechCorp Inc.', employerId: '1', status: CandidateStatus.ACTIVE, skills: ['JavaScript', 'Angular', 'React'], experience: 5, resume: 'sarah_resume.pdf', notes: 'Excellent communicator and team player.', createdAt: new Date('2024-01-15'), updatedAt: new Date('2024-12-28') },
    { id: '2', firstName: 'Michael', lastName: 'Chen', email: 'michael.chen@email.com', phoneNumber: '+1 (555) 987-6543', clientName: 'DataSoft LLC', employerId: '1', status: CandidateStatus.INTERVIEWED, skills: ['Python', 'Django', 'PostgreSQL'], experience: 3, resume: 'michael_resume.pdf', notes: 'Strong backend developer.', createdAt: new Date('2024-02-10'), updatedAt: new Date('2024-12-27') },
    { id: '3', firstName: 'Emily', lastName: 'Davis', email: 'emily.davis@email.com', phoneNumber: '+1 (555) 456-7890', clientName: 'InnovateTech', employerId: '1', status: CandidateStatus.HIRED, skills: ['Java', 'Spring Boot', 'Microservices'], experience: 7, resume: 'emily_resume.pdf', notes: 'Recently hired for microservices project.', createdAt: new Date('2024-03-05'), updatedAt: new Date('2024-12-26') },
    { id: '4', firstName: 'David', lastName: 'Wilson', email: 'david.wilson@email.com', phoneNumber: '+1 (555) 654-3210', clientName: 'TechCorp Inc.', employerId: '1', status: CandidateStatus.REJECTED, skills: ['C#', '.NET', 'Azure'], experience: 4, resume: 'david_resume.pdf', notes: 'Needs improvement in cloud skills.', createdAt: new Date('2024-04-12'), updatedAt: new Date('2024-12-25') },
    { id: '5', firstName: 'Priya', lastName: 'Singh', email: 'priya.singh@email.com', phoneNumber: '+91 98765 43210', clientName: 'DataSoft LLC', employerId: '2', status: CandidateStatus.ACTIVE, skills: ['Angular', 'TypeScript', 'RxJS'], experience: 6, resume: 'priya_resume.pdf', notes: 'Frontend specialist.', createdAt: new Date('2024-05-20'), updatedAt: new Date('2024-12-20') },
    { id: '6', firstName: 'Carlos', lastName: 'Martinez', email: 'carlos.martinez@email.com', phoneNumber: '+34 612 345 678', clientName: 'InnovateTech', employerId: '2', status: CandidateStatus.ACTIVE, skills: ['Vue.js', 'Node.js', 'MongoDB'], experience: 4, resume: 'carlos_resume.pdf', notes: 'Full stack developer.', createdAt: new Date('2024-06-10'), updatedAt: new Date('2024-12-19') },
    { id: '7', firstName: 'Anna', lastName: 'Petrova', email: 'anna.petrova@email.com', phoneNumber: '+7 495 123-45-67', clientName: 'TechCorp Inc.', employerId: '3', status: CandidateStatus.INTERVIEWED, skills: ['Java', 'Kotlin', 'Android'], experience: 5, resume: 'anna_resume.pdf', notes: 'Mobile developer.', createdAt: new Date('2024-07-15'), updatedAt: new Date('2024-12-18') },
    { id: '8', firstName: 'John', lastName: 'Smith', email: 'john.smith@email.com', phoneNumber: '+1 (555) 222-3333', clientName: 'DataSoft LLC', employerId: '2', status: CandidateStatus.HIRED, skills: ['PHP', 'Laravel', 'MySQL'], experience: 8, resume: 'john_resume.pdf', notes: 'Backend expert.', createdAt: new Date('2024-08-01'), updatedAt: new Date('2024-12-17') },
    { id: '9', firstName: 'Linda', lastName: 'Nguyen', email: 'linda.nguyen@email.com', phoneNumber: '+84 912 345 678', clientName: 'InnovateTech', employerId: '3', status: CandidateStatus.ACTIVE, skills: ['React', 'Redux', 'Sass'], experience: 3, resume: 'linda_resume.pdf', notes: 'UI/UX designer.', createdAt: new Date('2024-09-05'), updatedAt: new Date('2024-12-16') },
    { id: '10', firstName: 'Mohammed', lastName: 'Ali', email: 'mohammed.ali@email.com', phoneNumber: '+971 50 123 4567', clientName: 'TechCorp Inc.', employerId: '1', status: CandidateStatus.REJECTED, skills: ['Python', 'Flask', 'Docker'], experience: 2, resume: 'mohammed_resume.pdf', notes: 'Junior developer.', createdAt: new Date('2024-10-12'), updatedAt: new Date('2024-12-15') },
    { id: '11', firstName: 'Julia', lastName: 'Klein', email: 'julia.klein@email.com', phoneNumber: '+49 151 23456789', clientName: 'DataSoft LLC', employerId: '2', status: CandidateStatus.ACTIVE, skills: ['Go', 'Kubernetes', 'Cloud'], experience: 6, resume: 'julia_resume.pdf', notes: 'DevOps engineer.', createdAt: new Date('2024-11-20'), updatedAt: new Date('2024-12-14') },
    { id: '12', firstName: 'Omar', lastName: 'Farouk', email: 'omar.farouk@email.com', phoneNumber: '+20 100 123 4567', clientName: 'InnovateTech', employerId: '3', status: CandidateStatus.HIRED, skills: ['Ruby', 'Rails', 'PostgreSQL'], experience: 7, resume: 'omar_resume.pdf', notes: 'Senior backend developer.', createdAt: new Date('2024-12-01'), updatedAt: new Date('2024-12-13') },
    { id: '13', firstName: 'Sophia', lastName: 'Lee', email: 'sophia.lee@email.com', phoneNumber: '+82 10-1234-5678', clientName: 'TechCorp Inc.', employerId: '1', status: CandidateStatus.INTERVIEWED, skills: ['Swift', 'iOS', 'UI Design'], experience: 4, resume: 'sophia_resume.pdf', notes: 'iOS developer.', createdAt: new Date('2024-12-10'), updatedAt: new Date('2024-12-12') },
    { id: '14', firstName: 'Raj', lastName: 'Patel', email: 'raj.patel@email.com', phoneNumber: '+91 99876 54321', clientName: 'DataSoft LLC', employerId: '2', status: CandidateStatus.ACTIVE, skills: ['Angular', 'Node.js', 'Express'], experience: 5, resume: 'raj_resume.pdf', notes: 'Full stack developer.', createdAt: new Date('2024-12-15'), updatedAt: new Date('2024-12-11') },
    { id: '15', firstName: 'Maria', lastName: 'Garcia', email: 'maria.garcia@email.com', phoneNumber: '+34 699 123 456', clientName: 'InnovateTech', employerId: '3', status: CandidateStatus.HIRED, skills: ['Java', 'Spring', 'Hibernate'], experience: 6, resume: 'maria_resume.pdf', notes: 'Enterprise Java specialist.', createdAt: new Date('2024-12-20'), updatedAt: new Date('2024-12-10') }
  ];

  getCandidates(): Candidate[] {
    return [...this.candidates];
  }
}
